table fUnitsSold
	lineageTag: 220f064e-ec71-4608-8276-b2ca3bc46038

	measure 'Units Sold' = CALCULATE(SUM(fUnitsSold[Value]))
		formatString: #,0
		lineageTag: cf23e9ba-95ff-429a-901d-b2646dec7008

	measure 'Units Sold & predicted' = fUnitsSold[Units Sold] + fUnitsSalesPredicted[Units Prediction]
		formatString: 0
		lineageTag: 660f8ca0-c512-41f7-a2f2-d1dea618f849

	measure 'Unit Sales YTD' = CALCULATE(fUnitsSold[Units Sold],YEAR(dDate[Date]) = Year(MAX(fUnitsSold[Date])))
		formatString: 0
		lineageTag: e55d9d81-5c88-4f26-a644-d66ee61a1e40

	measure 'Unit Sales QTD' = CALCULATE([Units Sold],YEAR(dDate[Date]) = Year(MAX(fUnitsSold[Date])),QUARTER(dDate[Date]) = QUARTER(MAX(fUnitsSold[Date])))
		formatString: 0
		lineageTag: 24dd8680-4fdc-454f-9e9c-a36d2cf780cb

	column 'Qtr & Year'
		dataType: string
		lineageTag: 11231a59-9680-41f2-be07-2cb081dcde73
		summarizeBy: none
		sourceColumn: Qtr & Year

		annotation SummarizationSetBy = Automatic

	column Model
		dataType: string
		lineageTag: 32024e47-7ce4-4648-b87e-2a4a49a8915a
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: c6a28c99-492f-4e92-85c2-89472fc0025d
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Date = DATE(Value(RIGHT(fUnitsSold[Qtr & Year],4)),VALUE(Right(LEFT(fUnitsSold[Qtr & Year],2),1))*3,1)
		formatString: General Date
		lineageTag: d5142460-6d94-499d-89fd-bcbe70a67515
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fUnitsSold = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\Personal Projects\Power BI\Tesla Dashboard\Assets\Dataset.xlsx"), null, true),
				    #"Sales Units_Sheet" = Source{[Item="Sales Units",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Sales Units_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type text}, {"Model S", Int64.Type}, {"Model X", Int64.Type}, {"Model 3", Int64.Type}, {"Model Y", Int64.Type}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"Date"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Model"}, {"Date", "Qtr & Year"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

